### ISSUE TITLE
How to set up server

### ISSUE THREAD

**Issue by joehoyle** [fernyb/Sequel-J#1]
Hi There,

I am very interested in the Cappuccino side of this project and wondered if you had any instructions on how to get the server side up and running. I don't really have any experience with ruby, but I have it installed (OS X Snow Leopard). My machine is configured for PHP / MySQL / Apache2 setup.

I was also wondering how closely coupled with the server the client will be? How lightweight is your backend, I though perhaps you were just passing SQL queries to a simple rest file which passed it to mysql - this way you could easily support different languages (for whatever reason).

Thanks!

**Comment by fernyb** [comment]
The server is used to query and return the results back as JSON. There is never SQL statements being sent to the server. 
for returning the schema of the a table I would call the endpoint "/show_create_table/:table_name"
replacing :table_name with the actual table name and all request for now require that username, password, host, database be sent in the query string. This may change in the future to be sent as a cookie.

You can take a look at the server code in "server/app.rb"

**Comment by fernyb** [comment]
If there is more questions about starting the server do let me know.
