### ISSUE TITLE
Add functionality for: Adding, Removing, Rename, Duplicate & Refresh tables

### ISSUE THREAD

**Issue by fernyb** [fernyb/Sequel-J#19]
### Add functionality for:
- Adding Tables
- Removing Tables
- Rename Tables
- Duplicate Tables
- Truncate Table
- Refresh Tables

**Comment by joehoyle** [comment]
Added Remove table to PHP api in 2dc1fe679c7a02b082067824220c17724500891c

**Comment by fernyb** [comment]
I think this completes the ticket.
