### ISSUE TITLE
Finish up the Content Tab

### ISSUE THREAD

**Issue by fernyb** [fernyb/Sequel-J#20]
Finish up the Content Tab functionality:
- Add new rows
- Remove selected rows
- Edit rows
- Refresh rows
- Navigate Rows by paging on right bottom side.

**Comment by guilhermeaiolfi** [comment]
Looks pretty advanced. I can't wait to have a chance to try it. Great work, fernyb.
One question, tho. Can't you use a infinite/virtual table to show the content of a table?
Cappuccino is very good in that kind of thing.

**Comment by fernyb** [comment]
@guilhermeaiolfi Do you mean show all the rows with no paging?

**Comment by guilhermeaiolfi** [comment]
Exaclty. Fetch them on demand as the user scroll down the table.

**Comment by fernyb** [comment]
@guilhermeaiolfi that sounds like a good idea, I'll add that as an issue.

**Comment by fernyb** [comment]
I think the Content Tab is finished for now. Will now close. Any new issues should open a new issue.
